config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    get 'reports/edit'
  end
  get 'reports/edit'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


 #customer側↓
scope module: :customer do
  #カスタマー
  resources :customers, only: [:edit, :update, :destroy] do
    #リレーション(kichenをフォロー)
        resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'my_recipe/' => 'customers#my_recipe'
    get 'my_report/' => 'customers#my_report'
    get 'receive_report/' => 'customers#receive_report'
  end
    get 'my_page/:id' => 'customers#show', as: 'my_page'
    get 'my_page/:id/edit' => 'customers#edit', as: 'edit_my_page'



  resources :lists, only: [:index, :destroy, :create, :update] do
    collection do
      delete 'lists/destroy_all' => 'lists#destroy_all'
    end
  end
  #レシピ
  resources :recipes do
    collection do
      get 'top'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'name_search'
      get 'search/:category_id', to: 'recipes#search', as: 'search_category'
    end
    #member do
      #get 'search'
    #end
    #いいね
    resource :favorites, only: [:create, :destroy]
    #手順
    resources :explanations, only: [:create, :edit, :update, :destroy]
    #コメント
    resource :comments, only: [:create, :destroy]

    #材料詳細
    resources :material_details, only: [:new, :create]
    #作ったreport
    resources :reports, only: [:new, :index, :create, :destroy]
    resources :materials
  end
    get 'recipe/evaluation' => 'homes#evaluation'
    get 'recipe/create_at' => 'homes#create_at'
    get 'recipe/view' => 'homes#view'
    get 'favorites' => 'favorites#index', as: 'favorites'
    #post 'recipes/id/confirm' => 'recipes#confirm'
   # get 'complete' => 'recipes#compleate'
    root to: 'homes#top'
end

namespace :admin do
  #トップページのルーティング

    get '/' => 'homes#top'

    #カスタマー
    resources :customers, only:[:index, :destroy]

    #材料
    resources :material_details, only:[:index, :new, :create, :edit, :update, :destroy]

    resources :categories, only:[:index, :new, :create, :destroy]
end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to request.referer
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController
  before_action :authenticate_customer!

  def create
      @comment = Comment.new(comment_params)
      @comment.save
      #recipe = Recipe.find(params[:recipe_id])
      #byebug
      #@explanations = recipe.explanations.where(recipe_id: recipe.id)
      @comments = Comment.where(explanation_id: params[:explanation_id])
      @parent_explanation_id = params[:explanation_id]
      # redirect_to request.referer
  end

  def destroy
      @comment = Comment.find(params[:comment_id])
      @comment.destroy
      @comments = Comment.where(explanation_id: params[:explanation_id])
      @parent_explanation_id = params[:explanation_id]
  end

private

  def comment_params
    params.require(:comment).permit(:customer_id, :explanation_id, :comment)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController


  def show
    @customer = Customer.find(params[:id])
    @recipes = @customer.recipes.page(params[:page]).per(4)
    @recipeds = @customer.recipes.page(params[:page]).per(8)
    @reports = Report.where(customer_id: @customer.id).page(params[:page]).per(8)
  end

  def edit
    @customer = Customer.find(params[:id])
    redirect_to edit_customer_path(current_customer.id) unless current_customer.id == @customer.id
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       redirect_to my_page_path(@customer)
    else
      render 'edit'
    end
  end

  def my_recipe
    @customer = Customer.find(params[:customer_id])
    @recipes = @customer.recipes.page(params[:page]).order("created_at desc").per(6)
  end

  def my_report
    @customer = Customer.find(params[:customer_id])
    @reports = @customer.reports.page(params[:page]).per(6).order("created_at desc")
  end

  def receive_report
    @customer = Customer.find(params[:customer_id])
    #byebug
    @recipeds = @customer.recipes.page(params[:page]).per(8).order("created_at desc")
    #@recipes = current_customer.recipes.map{|m| m.reports}.map{|m| m}
  end

  private

  def customer_params
    params.require(:customer).permit(:profile_image, :bg_image, :name, :profile)
  end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  before_action :authenticate_customer!

  def create
    @recipe = Recipe.find(params[:recipe_id])
    favorite = Favorite.new(customer_id: current_customer.id, recipe_id: @recipe.id)
    favorite.save
    #redirect_to request.referer
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    favorite = Favorite.find_by(customer_id: current_customer.id, recipe_id: @recipe.id)
    favorite.destroy
    #redirect_to request.referer
  end

  def index
    @favorites = current_customer.favorites.order(created_at: 'DESC').page(params[:page]).per(6)
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  before_action :set_parents

    def top
      @recipes = Recipe.page(params[:page]).per(4).order("created_at desc")
      #evaluation_avgここで定義
      @reports = Report.group(:recipe_id).select("recipe_id, AVG(evaluation) AS evaluation_avg").order("evaluation_avg desc").page(params[:page]).per(4)
      # binding.irb
      recipes = Recipe.all
      @recipe_pvs = recipes.order(impressions_count: 'DESC').page(params[:page]).per(4)

      # recipes.each do |recipe|これを並べたい
      #   materials = recipe.materials
      #   roughs = recipe.materials.map{|m| m.rough/100}
      #   array = [*0.. roughs.count-1]
      #   @calorie = (array.map{|m| roughs[m]*MaterialDetail.where(id: materials.pluck(:material_detail_id)).pluck(:calorie)[m]}.sum*(100/ recipe.materials.sum(:rough))).round(1)
      # end

      respond_to do |format|
        format.html
        format.json do
          if params[:parent_id]
            @childrens = Category.find(params[:parent_id]).children
          elsif params[:children_id]
            @grandChilds = Category.find(params[:children_id]).children
          elsif params[:gcchildren_id]
            @parents = Category.where(id: params[:gcchildren_id])
          end
        end
       end
    end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def evaluation
    @reports = Report.group(:recipe_id).select("recipe_id, AVG(evaluation) AS evaluation_avg").order("evaluation_avg desc").page(params[:page]).per(6)
  end

  def view
    recipes = Recipe.all
   @recipe_pvs = recipes.order(impressions_count: 'DESC').page(params[:page]).per(6)
  end

  def create_at
    @recipes = Recipe.page(params[:page]).per(6).order("created_at desc")
  end

end

app/controllers/customer/lists_controller.rb
class Customer::ListsController < ApplicationController
  before_action :authenticate_customer!
  def index
    @lists = current_customer.lists

  end

  def create
      @list = List.new(list_params)
      @material_detail = MaterialDetail.find(params[:material_detail_id])
      @list.save

      redirect_to request.referer
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to request.referer
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to request.referer
  end

  def destroy_all
    products = current_customer.lists
    products.destroy_all
    redirect_to request.referer
  end

  private

  def list_params
    params.require(:list).permit(:customer_id, :material_detail_id, :memo)
  end

end

app/controllers/customer/material_details_controller.rb
class Customer::MaterialDetailsController < ApplicationController
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/recipes_controller.rb
class Customer::RecipesController < ApplicationController
  before_action :set_parents
  before_action :authenticate_customer!, except: [:show]
  #before_action :check_validates

  def index
    #@recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @material = @recipe.materials.build
    @material_detail = @material.build_material_detail
    @explanation = @recipe.explanations.build({})
    #byebug
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @error_message = nil
    #byebug
    if check_validates && @recipe.save
      redirect_to root_path
    else
      @error_message = "同じ材料は登録できません(デフォルトで表示しています)"
      # @explanation =  Recipe.new(recipe_params).explanations.build
      render 'new'
      #byebug
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    impressionist(@recipe, nil, unique: [:ip_address])
    @explanations = @recipe.explanations
    @materials = @recipe.materials
    #平均点
    @reports = @recipe.reports
    if @reports.exists?
      @average = @reports.average(:evaluation).round(1)
    end
    @list = List.new
    @mylists = List.where(customer_id: current_customer)
    @comment = Comment.new
    @category_id = @recipe.category_id
    @category_grandchild = Category.find(@category_id)#レシピが持ってる一番下のカテゴリ
    @category_child = @category_grandchild.parent
    #@category_parent = @category_grandchild.parent.parent

  end

  def edit
    @recipe = Recipe.find(params[:id])
    redirect_to new_customer_session_path unless customer_signed_in?
    if customer_signed_in?
      redirect_to root_path unless current_customer == @recipe.customer
    end

  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_path
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def search
    @category = Category.find(params[:category_id])#選択中のカテゴリ
      #if @category.indirects.children == nil && @category.parent == nil
        #自分と子供と孫を表示
      #elsif @category.children.children == nil && @category.parent.parent == nil
        #@recipes = Recipe.where(category_id: @category.indirect_ids)#自分と孫を表示
      #elsif @category.children == nil　&& @category.parent.parent.parent == nil #自分が孫の時
        @recipes = @category.recipes.page(params[:page]).per(6).order("created_at desc")
      #end
  end

  def find_item(category)
    category.each do |id|#選ばれたカテゴリの孫または子供のidをひとつずつ取り出す
      recipe_array = Recipe.where(category_id: id).order(created_at: :desc)#レシピの中で孫または子供のidを持っているレコードを取り出す。
      if recipe_array.present?
        recipe_array.each do |recipe|
          if recipe.present?
            @recipes.push(recipe)
          end
        end
      end
    end
  end

  private

  def recipe_params
     params.require(:recipe).permit(:image, :title, :time, :comment, :customer_id, :people, :category_id, explanations_attributes: [:id, :explanation, :process_image, :_destroy],
     materials_attributes: [:id, :amount, :rough, :material_detail_id, :_destroy])
  end

  def check_validates
    material_ids = []
    params[:recipe][:materials_attributes].each{|d| material_ids << d[1]["material_detail_id"]}
    material_ids.size == material_ids.uniq.size ? true : false
  end

end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/relationships_controller.rb
class Customer::RelationshipsController < ApplicationController

  def create
    @customer = Customer.find(params[:customer_id])
    current_customer.follow(params[:customer_id])
    #redirect_to request.referer
  end
  def destroy
    @customer = Customer.find(params[:customer_id])
    current_customer.unfollow(params[:customer_id])
    #redirect_to request.referer
  end

  def followings
     @customer = Customer.find(params[:customer_id])
     @customers = @customer.followings.page(params[:page]).per(8)
  end

  def followers
     @customer = Customer.find(params[:customer_id])
     @customers = @customer.followers.page(params[:page]).per(8)
  end

end

app/controllers/customer/reports_controller.rb
class Customer::ReportsController < ApplicationController
  #before_action :authenticate_customer!,except: [:new]

  def new
    @report = Report.new
    @recipe = Recipe.find(params[:recipe_id])
    redirect_to new_customer_session_path unless customer_signed_in?
  end

  def index
    @recipe = Recipe.find(params[:recipe_id])
    @reports = @recipe.reports
    #@reports = Report.where(recipe_id: @recipe.id)
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @report = Report.new(report_params)
    if @report.save
      redirect_to recipe_reports_path(@recipe)
    else
      render 'new'
    end
  end

  def destroy
     @report = Report.find(params[:id])
     @report.destroy
     redirect_to request.referer
  end

  private

  def report_params
    params.require(:report).permit(:image, :impression, :evaluation, :customer_id, :recipe_id)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/customer/homes/_index.html.erb
      <div class="row">
        <% recipes.each do |recipe| %>
          <div class="col-md-6 mb-5">
            <%= link_to recipe_path(recipe) do %>
              <div class="text-center">
                <div class="title-font-color midashi"  style="font-size: 30px;">
                  <strong><%= recipe.title.truncate(14) %></strong>
                </div>
              </div>
            <% end %>
            <div class="date-pa">
              <div class="date-font"><%= recipe.created_at.strftime('%Y/%m/%d  %H:%M:%S') %></div>
            </div>
            <%= link_to recipe_path(recipe) do %>
              <%= attachment_image_tag recipe, :image, fallback:"no_bg_image.jpg", class: "recipe-img-create img-fluid rounded center-img" %>
            <% end %>
          </div>
        <% end %>
        
      </div>
      <div class="row justify-content-center">
        <div class="col-md-4">
          <%= paginate recipes, theme: 'twitter-bootstrap-4' %>
        </div>
      </div>

app/views/customer/homes/create_at.html.erb
<div class="container-fluid ml-3 mr-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="row mt-3 mb-3 justify-content-center">
          <div class="border-top border-bottom text-center" style="width: 60%; border-color:#708090;">
            <h5 class="top-title-font">新着レシピ</h5>
          </div>
      </div>
      <%= render partial: 'index', locals: { recipes: @recipes} %>
    </div>
  </div>
</div>

app/views/customer/homes/evaluation.html.erb
<div class="container-fluid ml-3 mr-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="row mt-3 mb-3 justify-content-center">
          <div class="border-top border-bottom text-center" style="width: 60%; border-color:#708090;">
            <h5 class="top-title-font">評価の高いレシピ</h5>
          </div>
      </div>
        <div class="row">
          <% @reports.each do |recipe| %>
            <div class="col-md-6 mb-5">
              <%= link_to recipe_path(recipe.recipe) do %>
              <div class="text-center">
                <div class="title-font-color midashi"  style="font-size: 30px;">
                  <strong><%= recipe.recipe.title.truncate(14) %></strong>
                </div>
              </div>
              <% end %>
              <div class="date-pa">
                <div class="date-font"><%= recipe.recipe.created_at.strftime('%Y/%m/%d  %H:%M:%S') %></div>
              </div>
              <%= link_to recipe_path(recipe.recipe) do %>
                <%= attachment_image_tag recipe.recipe, :image, fallback:"no_bg_image.jpg", class: "recipe-img-create img-fluid rounded center-img" %>
              <% end %>
              <div class="submit-prace mt-3">
                <span id="star-rate-average_<%= recipe.recipe.id %>"></span>
                (<%= recipe.evaluation_avg.round(1) %>点)
                <script>
                  $('#star-rate-average_<%= recipe.recipe.id %>').empty();
                  $('#star-rate-average_<%= recipe.recipe.id %>').raty({
                    size: 36,
                    starOff: "<%= asset_path('star-off.png') %>",
                    starOn: "<%= asset_path('star-on.png') %>",
                    starHalf: "<%= asset_path('star-half.png') %>",
                    half: true,
                    readOnly: true,
                   score: <%= recipe.evaluation_avg.round(1) %>,
                  });
                </script>
              </div>
            </div>
          <% end %>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-4">
            <%= paginate @reports, theme: 'twitter-bootstrap-4' %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/customer/homes/top.html.erb
  <div class="container w-100 bg">
    <div class="row justify-content-center">
      <div class="col-12 top-image">
        <ul>自炊を始めたいけど料理の知識がない方へ
          <li>質問できる！</li>
          <li>栄養素表示が見られる！</li>
          そんなレシピサイトです。
        </ul>
      </div>
      <div class="col-md-3 categories">
        <div class="item-categories">
          <p class="midashi category-size">
            カテゴリーから探す
          </p>
          <div id="tree_menu">
            <ul class="categoryTree">
              <% @parents.each do |parent| %>
                <li class="category_parent category-point">
                  <%#= link_to search_category_recipes_path(parent) do %>
                    <!--<input type="button" value="<%= parent.name %>" name="<%= parent.id %>" class="parent_btn btn pt-0 pb-0 mb-1">-->
                    <input type="button" value="<%= parent.name %>" id="<%= parent.id %>" class="parent_btn btn pt-0 pb-0 mb-1 category-font-p">
                  <%# end %>
                  <ul class="ml-3">
                    <% parent.children.each do |child| %>
                      <li>
                        <%#= link_to search_category_recipes_path(child) do %>
                          <input type="button" value="<%= child.name %>" id="<%= child.id %>" class="parent_btn btn pt-0 pb-0 mb-1 category-font-c">
                        <%# end %>
                        <ul class="ml-3">
                          <% child.children.each do |gchild| %>
                            <li>
                              <%= link_to search_category_recipes_path(gchild) do %>
                                <input type="button" value="<%= gchild.name %>" id="<%= gchild.id %>" class="parent_btn btn pt-0 pb-0 mb-1 btn-sm category-font-c grandchild">
                              <% end %>
                            </li>
                          <% end %>
                        </ul>
                      </li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-lg-7 col-md-10 mb-5">

        <div class="mb-5">
          <div class="row mt-3 mb-3 justify-content-center">
            <div class="border-top border-bottom text-center" style="width: 60%; border-color:#708090;">
              <h5 class="mt-2 top-title-font"><a>評価が高いレシピ</a></h5>
            </div>
          </div>
          <div class="row">
            <% @reports.each do |report| %>
              <div class="col-lg-6 col-md-6 col-sm-12 mt-3 recipe-parent">
                <%= link_to recipe_path(report.recipe) do %>
                  <%= attachment_image_tag report.recipe, :image, fallback:"no_bg_image.jpg", class: "img-fluid recipe-img rounded" %>
                  <div class="title-font-color"><strong><%= report.recipe.title %></strong></div>
                <% end %>
                <div class="date-color"><%= report.recipe.created_at.strftime('%Y/%m/%d  %H:%M:%S') %></div>
                  <div>
                    <span id="star-rate-average_<%= report.recipe.id %>"></span>
                    (<%= report.evaluation_avg.round(1) %>点)
                      <script>
                        $('#star-rate-average_<%= report.recipe.id %>').empty();
                        $('#star-rate-average_<%= report.recipe.id %>').raty({
                          size: 36,
                          starOff: "<%= asset_path('star-off.png') %>",
                          starOn: "<%= asset_path('star-on.png') %>",
                          starHalf: "<%= asset_path('star-half.png') %>",
                          half: true,
                          readOnly: true,
                          score: <%= report.evaluation_avg.round(1) %>,
                        });
                    </script>
                  </div>
              </div>
            <% end %>
          </div>
          <div class="col-md-12 submit-prace mt-5 itiranbtn ">
              <%= link_to "一覧を表示", recipe_evaluation_path %>
          </div>
        </div>

        <div class="mb-5">
          <div class="row mt-3 mb-3 justify-content-center">
            <div class="border-top border-bottom text-center" style="width: 60%; border-color:#708090;">
              <h5 class="mt-2 top-title-font">新着レシピ</h5>
            </div>
          </div>
          <div class="row">
            <% @recipes.each do |recipe| %>
              <div class="col-lg-6 col-md-6 col-sm-12 mt-3 recipe-parent">
                <%= link_to recipe_path(recipe), class:"userList" do %>
                  <%= attachment_image_tag recipe, :image, fallback:"no_bg_image.jpg", class: "img-fluid recipe-img rounded" %>
                  <div class="title-font-color"><strong><%= recipe.title %></strong></div>
                <% end %>
                <div class="date-color"><%= recipe.created_at.strftime('%Y/%m/%d  %H:%M:%S') %></div>
              </div>
            <% end %>
            <div class="col-md-12 submit-prace mt-4 itiranbtn">
              <%= link_to "一覧を表示", recipe_create_at_path %>
            </div>
          </div>
        </div>

        <div class="mb-5">
          <div class="row mt-3 mb-3 justify-content-center">
            <div class="border-top border-bottom text-center" style="width: 60%; border-color:#708090;">
              <h5 class="mt-2 top-title-font">注目のレシピ</h5>
            </div>
          </div>
          <div class="row">
              <% @recipe_pvs.each do |recipe| %>
                <div class="col-lg-6 col-md-6 col-sm-12 mt-3 view-img recipe-parent">
                  <%= link_to recipe_path(recipe) do %>
                    <div><%= attachment_image_tag recipe, :image, fallback:"no_bg_image.jpg", class: "img-fluid recipe-img rounded" %></div>
                    <div class="title-font-color"><strong><%= recipe.title %></strong></div>
                  <% end %>
                  <div class="date-color"><%= recipe.created_at.strftime('%Y/%m/%d  %H:%M:%S') %></div>
                </div>
              <% end %>
          </div>
          <div class="row">
            <div class="col-md-12 submit-prace mt-4 itiranbtn">
              <%= link_to "一覧を表示", recipe_view_path %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 categories category-hide">
        <div class="item-categories">
          <p class="midashi category-size">
            カテゴリーから探す
          </p>
          <div id="tree_menu">
            <ul class="categoryTree">
              <% @parents.each do |parent| %>
                <li class="category_parent category-point">
                  <%#= link_to search_category_recipes_path(parent) do %>
                    <!--<input type="button" value="<%= parent.name %>" name="<%= parent.id %>" class="parent_btn btn pt-0 pb-0 mb-1">-->
                    <input type="button" value="<%= parent.name %>" id="<%= parent.id %>" class="parent_btn btn pt-0 pb-0 mb-1 category-font-p">
                  <%# end %>
                  <ul class="ml-3">
                    <% parent.children.each do |child| %>
                      <li>
                        <%#= link_to search_category_recipes_path(child) do %>
                          <input type="button" value="<%= child.name %>" id="<%= child.id %>" class="parent_btn btn pt-0 pb-0 mb-1 category-font-c">
                        <%# end %>
                        <ul class="ml-3">
                          <% child.children.each do |gchild| %>
                            <li>
                              <%= link_to search_category_recipes_path(gchild) do %>
                                <input type="button" value="<%= gchild.name %>" id="<%= gchild.id %>" class="parent_btn btn pt-0 pb-0 mb-1 btn-sm category-font-c grandchild">
                              <% end %>
                            </li>
                          <% end %>
                        </ul>
                      </li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/customer/homes/view.html.erb
<div class="container-fluid ml-3 mr-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="row mt-3 mb-3 justify-content-center">
          <div class="border-top border-bottom text-center" style="width: 60%; border-color:#708090;">
            <h5 class="top-title-font">注目のレシピ</h5>
          </div>
      </div>
      <%= render partial: 'index', locals: { recipes: @recipe_pvs} %>
    </div>
  </div>
</div>