config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    get 'reports/edit'
  end
  get 'reports/edit'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


 #customer側↓
scope module: :customer do
  #カスタマー
  resources :customers, only: [:edit, :update, :destroy] do
    #リレーション(kichenをフォロー)
        resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'my_recipe/' => 'customers#my_recipe'
    get 'my_report/' => 'customers#my_report'
    get 'receive_report/' => 'customers#receive_report'
  end
    get 'my_page/:id' => 'customers#show', as: 'my_page'
    get 'my_page/:id/edit' => 'customers#edit', as: 'edit_my_page'



  resources :lists, only: [:index, :destroy, :create, :update] do
    collection do
      delete 'lists/destroy_all' => 'lists#destroy_all'
    end
  end
  #レシピ
  resources :recipes do
    collection do
      get 'top'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'name_search'
      get 'search/:category_id', to: 'recipes#search', as: 'search_category'
    end
    #member do
      #get 'search'
    #end
    #いいね
    resource :favorites, only: [:create, :destroy]
    #手順
    resources :explanations, only: [:create, :edit, :update, :destroy]
    #コメント
    resource :comments, only: [:create, :destroy]

    #材料詳細
    resources :material_details, only: [:new, :create]
    #作ったreport
    resources :reports, only: [:new, :index, :create, :destroy]
    resources :materials
  end
    get 'recipe/evaluation' => 'homes#evaluation'
    get 'recipe/create_at' => 'homes#create_at'
    get 'recipe/view' => 'homes#view'
    get 'favorites' => 'favorites#index', as: 'favorites'
    #post 'recipes/id/confirm' => 'recipes#confirm'
   # get 'complete' => 'recipes#compleate'
    root to: 'homes#top'
end

namespace :admin do
  #トップページのルーティング

    get '/' => 'homes#top'

    #カスタマー
    resources :customers, only:[:index, :destroy]

    #材料
    resources :material_details, only:[:index, :new, :create, :edit, :update, :destroy]

    resources :categories, only:[:index, :new, :create, :destroy]
end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to request.referer
  end
end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController
  before_action :authenticate_customer!

  def create
      @comment = Comment.new(comment_params)
      @comment.save
      #recipe = Recipe.find(params[:recipe_id])
      #byebug
      #@explanations = recipe.explanations.where(recipe_id: recipe.id)
      @comments = Comment.where(explanation_id: params[:explanation_id])
      @parent_explanation_id = params[:explanation_id]
      # redirect_to request.referer
  end

  def destroy
      @comment = Comment.find(params[:comment_id])
      @comment.destroy
      @comments = Comment.where(explanation_id: params[:explanation_id])
      @parent_explanation_id = params[:explanation_id]
  end

private

  def comment_params
    params.require(:comment).permit(:customer_id, :explanation_id, :comment)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController


  def show
    @customer = Customer.find(params[:id])
    @recipes = @customer.recipes.page(params[:page]).per(4)
    @recipeds = @customer.recipes.page(params[:page]).per(8)
    @reports = Report.where(customer_id: @customer.id).page(params[:page]).per(8)
  end

  def edit
    @customer = Customer.find(params[:id])
    redirect_to edit_customer_path(current_customer.id) unless current_customer.id == @customer.id
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       redirect_to my_page_path(@customer)
    else
      render 'edit'
    end
  end

  def my_recipe
    @customer = Customer.find(params[:customer_id])
    @recipes = @customer.recipes.page(params[:page]).order("created_at desc").per(6)
  end

  def my_report
    @customer = Customer.find(params[:customer_id])
    @reports = @customer.reports.page(params[:page]).per(6).order("created_at desc")
  end

  def receive_report
    @customer = Customer.find(params[:customer_id])
    #byebug
    @recipeds = @customer.recipes.page(params[:page]).per(8).order("created_at desc")
    #@recipes = current_customer.recipes.map{|m| m.reports}.map{|m| m}
  end

  private

  def customer_params
    params.require(:customer).permit(:profile_image, :bg_image, :name, :profile)
  end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  before_action :authenticate_customer!

  def create
    @recipe = Recipe.find(params[:recipe_id])
    favorite = Favorite.new(customer_id: current_customer.id, recipe_id: @recipe.id)
    favorite.save
    #redirect_to request.referer
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    favorite = Favorite.find_by(customer_id: current_customer.id, recipe_id: @recipe.id)
    favorite.destroy
    #redirect_to request.referer
  end

  def index
    @favorites = current_customer.favorites.order(created_at: 'DESC').page(params[:page]).per(6)
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  before_action :set_parents

    def top
      @recipes = Recipe.page(params[:page]).per(4).order("created_at desc")
      #evaluation_avgここで定義
      @reports = Report.group(:recipe_id).select("recipe_id, AVG(evaluation) AS evaluation_avg").order("evaluation_avg desc").page(params[:page]).per(4)
      # binding.irb
      recipes = Recipe.all
      @recipe_pvs = recipes.order(impressions_count: 'DESC').page(params[:page]).per(4)

      # recipes.each do |recipe|これを並べたい
      #   materials = recipe.materials
      #   roughs = recipe.materials.map{|m| m.rough/100}
      #   array = [*0.. roughs.count-1]
      #   @calorie = (array.map{|m| roughs[m]*MaterialDetail.where(id: materials.pluck(:material_detail_id)).pluck(:calorie)[m]}.sum*(100/ recipe.materials.sum(:rough))).round(1)
      # end

      respond_to do |format|
        format.html
        format.json do
          if params[:parent_id]
            @childrens = Category.find(params[:parent_id]).children
          elsif params[:children_id]
            @grandChilds = Category.find(params[:children_id]).children
          elsif params[:gcchildren_id]
            @parents = Category.where(id: params[:gcchildren_id])
          end
        end
       end
    end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def evaluation
    @reports = Report.group(:recipe_id).select("recipe_id, AVG(evaluation) AS evaluation_avg").order("evaluation_avg desc").page(params[:page]).per(6)
  end

  def view
    recipes = Recipe.all
   @recipe_pvs = recipes.order(impressions_count: 'DESC').page(params[:page]).per(6)
  end

  def create_at
    @recipes = Recipe.page(params[:page]).per(6).order("created_at desc")
  end

end

app/controllers/customer/lists_controller.rb
class Customer::ListsController < ApplicationController
  before_action :authenticate_customer!
  def index
    @lists = current_customer.lists

  end

  def create
      @list = List.new(list_params)
      @material_detail = MaterialDetail.find(params[:material_detail_id])
      @list.save

      redirect_to request.referer
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to request.referer
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to request.referer
  end

  def destroy_all
    products = current_customer.lists
    products.destroy_all
    redirect_to request.referer
  end

  private

  def list_params
    params.require(:list).permit(:customer_id, :material_detail_id, :memo)
  end

end

app/controllers/customer/material_details_controller.rb
class Customer::MaterialDetailsController < ApplicationController
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/recipes_controller.rb
class Customer::RecipesController < ApplicationController
  before_action :set_parents
  before_action :authenticate_customer!, except: [:show]
  #before_action :check_validates

  def index
    #@recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @material = @recipe.materials.build
    @material_detail = @material.build_material_detail
    @explanation = @recipe.explanations.build({})
    #byebug
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @error_message = nil
    #byebug
    if check_validates && @recipe.save
      redirect_to root_path
    else
      @error_message = "同じ材料は登録できません(デフォルトで表示しています)"
      # @explanation =  Recipe.new(recipe_params).explanations.build
      render 'new'
      #byebug
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    impressionist(@recipe, nil, unique: [:ip_address])
    @explanations = @recipe.explanations
    @materials = @recipe.materials
    #平均点
    @reports = @recipe.reports
    if @reports.exists?
      @average = @reports.average(:evaluation).round(1)
    end
    @list = List.new
    @mylists = List.where(customer_id: current_customer)
    @comment = Comment.new
    @category_id = @recipe.category_id
    @category_grandchild = Category.find(@category_id)#レシピが持ってる一番下のカテゴリ
    @category_child = @category_grandchild.parent
    #@category_parent = @category_grandchild.parent.parent

  end

  def edit
    @recipe = Recipe.find(params[:id])
    redirect_to new_customer_session_path unless customer_signed_in?
    if customer_signed_in?
      redirect_to root_path unless current_customer == @recipe.customer
    end

  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_path
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def search
    @category = Category.find(params[:category_id])#選択中のカテゴリ
      #if @category.indirects.children == nil && @category.parent == nil
        #自分と子供と孫を表示
      #elsif @category.children.children == nil && @category.parent.parent == nil
        #@recipes = Recipe.where(category_id: @category.indirect_ids)#自分と孫を表示
      #elsif @category.children == nil　&& @category.parent.parent.parent == nil #自分が孫の時
        @recipes = @category.recipes.page(params[:page]).per(6).order("created_at desc")
      #end
  end

  def find_item(category)
    category.each do |id|#選ばれたカテゴリの孫または子供のidをひとつずつ取り出す
      recipe_array = Recipe.where(category_id: id).order(created_at: :desc)#レシピの中で孫または子供のidを持っているレコードを取り出す。
      if recipe_array.present?
        recipe_array.each do |recipe|
          if recipe.present?
            @recipes.push(recipe)
          end
        end
      end
    end
  end

  private

  def recipe_params
     params.require(:recipe).permit(:image, :title, :time, :comment, :customer_id, :people, :category_id, explanations_attributes: [:id, :explanation, :process_image, :_destroy],
     materials_attributes: [:id, :amount, :rough, :material_detail_id, :_destroy])
  end

  def check_validates
    material_ids = []
    params[:recipe][:materials_attributes].each{|d| material_ids << d[1]["material_detail_id"]}
    material_ids.size == material_ids.uniq.size ? true : false
  end

end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/relationships_controller.rb
class Customer::RelationshipsController < ApplicationController

  def create
    @customer = Customer.find(params[:customer_id])
    current_customer.follow(params[:customer_id])
    #redirect_to request.referer
  end
  def destroy
    @customer = Customer.find(params[:customer_id])
    current_customer.unfollow(params[:customer_id])
    #redirect_to request.referer
  end

  def followings
     @customer = Customer.find(params[:customer_id])
     @customers = @customer.followings.page(params[:page]).per(8)
  end

  def followers
     @customer = Customer.find(params[:customer_id])
     @customers = @customer.followers.page(params[:page]).per(8)
  end

end

app/controllers/customer/reports_controller.rb
class Customer::ReportsController < ApplicationController
  #before_action :authenticate_customer!,except: [:new]

  def new
    @report = Report.new
    @recipe = Recipe.find(params[:recipe_id])
    redirect_to new_customer_session_path unless customer_signed_in?
  end

  def index
    @recipe = Recipe.find(params[:recipe_id])
    @reports = @recipe.reports
    #@reports = Report.where(recipe_id: @recipe.id)
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @report = Report.new(report_params)
    if @report.save
      redirect_to recipe_reports_path(@recipe)
    else
      render 'new'
    end
  end

  def destroy
     @report = Report.find(params[:id])
     @report.destroy
     redirect_to request.referer
  end

  private

  def report_params
    params.require(:report).permit(:image, :impression, :evaluation, :customer_id, :recipe_id)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/comments_helper.rb
module Customer::CommentsHelper
end

app/views/customer/recipes/_comment.html.erb
 <% comments.each do |comment| %>
  <div>
    <div><strong><%= comment.customer.name %></strong></div>
    <div class="pl-1"><%= comment.comment %>
      <% if comment.customer.id == current_customer.id || comment.explanation.recipe.customer.id == current_customer.id %><!--レシピ投稿者とコメント投稿者のみ削除できる-->
        <%= link_to recipe_comments_path(recipe_id: comment.explanation.recipe, comment_id: comment.id, explanation_id: comment.explanation.id), method: :delete, remote: true do %>
           <i class="fas fa-trash-alt ml-4" style="color: red;"></i>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/customer/recipes/_list.html.erb
<% if customer_signed_in? %>
  <%= form_with model: list, url: lists_path(material_detail_id: material.id) do |f| %>
    <%= f.hidden_field :customer_id, :value => current_customer.id %>
    <%= f.hidden_field :material_detail_id, :value => material.material_detail.id %>
    <%= f.submit "買い物リストへ追加", class: "btn btn-secondary cart-moji" %>
  <% end %>
<% end %>

app/views/customer/recipes/show.html.erb
<div class="container pt-3 mb-5">
  <div class="d-flex justify-content-center">
      <h2 class="mr-3 recipe-title"><%= @recipe.title %></h2>
     <% if customer_signed_in? %>
        <span class="mt-3" id="favorite_buttons_<%= @recipe.id %>">
          <%= render "customer/favorites/favorite", recipe: @recipe %>
        </span>
      <% end %>
  </div>
  <div class="row justify-content-between">
    <div class="col-md-3 category-font">
      <strong>カテゴリ</strong>
      <% if @category_child == nil %><!--1個上が空-->
        <p><%= @category_grandchild.name %></p>
      <% elsif @category_grandchild.parent.parent == nil %><!--2個上が空-->
        <p><%= @category_child.name %> > <%= @category_grandchild.name %></p>
      <% else %>
        <p><%= @category_grandchild.parent.parent.name %> > <%= @category_child.name %> > <%= @category_grandchild.name %></p>
      <% end %>
    </div>
    <div class="col-md-4">
      <div class="text-right mt-2 recipe-moji">
        <% if @reports.exists? %>
          <span>平均評価：</span>
          <span id="star-rate-average"></span>
          <script>
            $('#star-rate-average').empty();
            $('#star-rate-average').raty({
              size: 36,
              starOff: "<%= asset_path('star-off.png') %>",
              starOn: "<%= asset_path('star-on.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              half: true,
              readOnly: true,
              score: <%= @average %>,
            });
          </script>
          (<%= @average %>点)
        <% else %>
          <span>平均評価：</span>
          <span id="star-rate-0"></span>
          <script>
            $('#star-rate-0').empty();
            //$(document).on('turbolinks:load', function() {
            $('#star-rate-0').raty({
              size: 36,
              starOff: "<%= asset_path('star-off.png') %>",
              starOn: "<%= asset_path('star-on.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              half: true,
              readOnly: true,
               score: <%= 0 %>,
            });
           // });
          </script>
          (<%= 0 %>点)
        <% end %>
      </div>
    </div>
  </div>
  <% if @recipe.time.present? %>
    <p class="text-right mb-0 recipe-moji">(調理時間<%= @recipe.time %>)</p>
  <% end %>


  <div class="row mb-5 mt-5 justify-content-center submit-prace align-items-start edit-hide">
    <div class="col-lg-3 col-md-7">
      <%= link_to Refile.attachment_url(@recipe, :image), 'data-lightbox':"recipe" do %>
        <%= attachment_image_tag @recipe, :image, :fill, 200, 200, class: "recipe-show-image rounded-start" %>
      <% end %>
    </div>
    <div class="col-lg-4 col-md-5">
      <div class=" border-bottom recipe-moji">
        <%= link_to my_page_path(@recipe.customer) do %>
          <%= attachment_image_tag @recipe.customer, :profile_image, fallback:"no-image-icon.jpg", class: "img-fluid rounded-circle",size: '50x50' %>
          <%= @recipe.customer.name %>
        <% end %>
      </div>
      <p class="comment-wrap recipe-moji"><%= @recipe.comment %></p>
    </div>

    <div>

    </div>

    <div class="col-md-3 text-center" style="height:120px; width: 50%;">
      <div class="w-60 pb-2 ml-4" >
        <%= link_to recipe_reports_path(@recipe) do %>
          <div class="bg-light text-center pt-2 pb-2 recipe-moji">みんなが作った数<%= @recipe.reports.count %>件</div>
        <% end %>
      </div>
      <div>
        <div class="btn btn-outline-warning"><%= link_to "作ったreportを書く", new_recipe_report_path(@recipe), class: "recipe-moji" %></div>
      </div>
      <div class="d-flex end">
        <% if customer_signed_in? %>
          <% if current_customer.id == @recipe.customer.id %>
            <div class="mr-2"><%= link_to "レシピ編集", edit_recipe_path(@recipe), class: "recipe-moji" %></div>
            <div><%= link_to "レシピ削除", recipe_path(@recipe), method: :delete, "data-confirm" => "レシピを削除しますか？", class: "recipe-moji" %></div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row mb-5 mt-5 justify-content-center submit-prace align-items-start defolt-none">
    <%= render 'customer/recipes/responsive', recipe: @recipe %>
  </div>


  <div class="row border-bottom border-top pt-3 justify-content-center">
    <div class="col-md-11">
      <h4 class="midashi">材料（<%= @recipe.people %>人分）</h4>
      <table class="row table table-striped text-center mb-5">
        <tbody class="col">
          <% @materials.each do |material| %>
            <tr>
              <td class="col-md-4 text-left recipe-moji"><%= material.material_detail.name %></td>
              <td class="col-md-1 col-sm-2 text-left recipe-moji"><%= material.amount %></td>
              <td class="col-md-2 pt-1 pb-1" id="material_<%= material.id %>">
                <% if customer_signed_in? %>
                  <% if @mylists.find_by(material_detail_id: material.material_detail.id).present? %>
                    <div class="list-present rounded-pill comment-wrap">すでに買い物リストに入っています</div>
                  <% else %>
                    <%= form_with model: @list, url: lists_path(material_detail_id: material.id) do |f| %>
                      <%= f.hidden_field :customer_id, :value => current_customer.id %>
                      <%= f.hidden_field :material_detail_id, :value => material.material_detail.id %>
                      <%= f.submit "買い物リストへ追加", class: "btn btn-secondary cart-moji " %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <h4 class="midashi">目安栄養素(100gあたり)</h4>
      <div class="row mb-5">
        <table class="col table text-center midashi">
          <thead>
            <th>カロリー(kcal)</th>
            <th>糖質(g)</th>
            <th>タンパク質(g)</th>
            <th>脂質(g)</th>
            <th>食物繊維(g)</th>
            <th>塩分(g)</th>
          </thead>
          <tbody>
            <td><%= @recipe.calorie %></td>
            <td><%= @recipe.sugar %></td>
            <td><%= @recipe.protein %></td>
            <td><%= @recipe.lipids %></td>
            <td><%= @recipe.dietary_fiber %></td>
            <td><%= @recipe.salt %></td>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md">
      <h4 class="midashi">作り方</h4>
      <div id="wrap">
        <div class="txt-show">
          <% @explanations.each_with_index do |explanation, i| %>
            <div>
              <div class="row mb-6 border-bottom pb-4 pt-2">
                <div class="col-md-6">
                  <div class="rounded text-center num-bg">
                    <h4 class="recipe-moji" style="color: #fff;"><%= i.to_i + 1 %></h4><!--レシピ順の番号をとりだしてる-->
                  </div>
                  <div class="recipe-moji"><%= explanation.explanation %></div>
                </div>
                <div class="col-md-3">
                  <%= link_to Refile.attachment_url(explanation, :process_image), 'data-lightbox':"explanation" do %>
                    <%= attachment_image_tag explanation, :process_image, class: "img-fluid", id: 'imageFile_' + i.to_s %>
                  <% end %>
                </div>

                <div class="col-md-3">
                  <button class="more align-self-center recipe-moji", id="comment_<%= i.to_s %>"></button>
                  <div class="txt-hide comment_<%= i.to_s %> pl-3">

                    <div class="mb-3 border-bottom pb-4 pt-2" id="children_comments_<%= explanation.id %>">
                      <% explanation.comments.each do |comment| %>
                        <div>
                          <div><strong><%= comment.customer.name %></strong></div>
                          <div class="pl-1"><%= comment.comment %>
                            <% if customer_signed_in? %>
                              <% if comment.customer.id == current_customer.id || comment.explanation.recipe.customer.id == current_customer.id %><!--レシピ投稿者とコメント投稿者のみ削除できる-->
                                <%= link_to recipe_comments_path(recipe_id: explanation.recipe, comment_id: comment.id, explanation_id: explanation.id), method: :delete, remote: true do %>
                                   <i class="fas fa-trash-alt ml-4" style="color: red;"></i>
                                <% end %>
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                      <% end %>
                    </div>

                    <% if customer_signed_in? %>
                      <%= form_with model: @comment, url: recipe_comments_path(recipe_id: explanation.recipe, explanation_id: explanation.id) do |f| %>
                        <div class="col-md-4"><%= f.text_area :comment, placeholder: "例）耳たぶくらいの固さって？", required: :true  %></div>
                        <%= f.hidden_field :customer_id, :value => current_customer.id %>
                        <%= f.hidden_field :explanation_id, :value => explanation.id %>
                        <div class="col-md-1"><%= f.submit "送信する", class: "btn btn-success" %></div>
                      <% end %>
                    <% else %>
                      <p class="midashi">コメントするにはログインしてください</p>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
          <div>
            <p class="date-color">投稿日：<%= @recipe.created_at.strftime('%Y/%m/%d') %></p>
          </div>
        </div>
    </div>
  </div>

</div>



<script>
  $(function(){
  $(".more").on("click", function() {
    target_id = $(this).attr("id")
    //$(this).toggleClass("on-click");
    $("." + target_id).slideToggle(1000);
  });
});
</script>