config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    get 'reports/edit'
  end
  get 'reports/edit'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


 #customer側↓
scope module: :customer do
  #カスタマー
  resources :customers, only: [:edit, :update, :destroy] do
    #リレーション(kichenをフォロー)
        resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'my_recipe/' => 'customers#my_recipe'
    get 'my_report/' => 'customers#my_report'
    get 'receive_report/' => 'customers#receive_report'
  end
    get 'my_page/:id' => 'customers#show', as: 'my_page'
    get 'my_page/:id/edit' => 'customers#edit', as: 'edit_my_page'



  resources :lists, only: [:index, :destroy, :create, :update] do
    collection do
      delete 'lists/destroy_all' => 'lists#destroy_all'
    end
  end
  #レシピ
  resources :recipes do
    collection do
      get 'top'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'name_search'
      get 'search/:category_id', to: 'recipes#search', as: 'search_category'
    end
    #member do
      #get 'search'
    #end
    #いいね
    resource :favorites, only: [:create, :destroy]
    #手順
    resources :explanations, only: [:create, :edit, :update, :destroy]
    #コメント
    resource :comments, only: [:create, :destroy]

    #材料詳細
    resources :material_details, only: [:new, :create]
    #作ったreport
    resources :reports, only: [:new, :index, :create, :destroy]
    resources :materials
  end
    get 'recipe/evaluation' => 'homes#evaluation'
    get 'recipe/create_at' => 'homes#create_at'
    get 'recipe/view' => 'homes#view'
    get 'favorites' => 'favorites#index', as: 'favorites'
    #post 'recipes/id/confirm' => 'recipes#confirm'
   # get 'complete' => 'recipes#compleate'
    root to: 'homes#top'
end

namespace :admin do
  #トップページのルーティング

    get '/' => 'homes#top'

    #カスタマー
    resources :customers, only:[:index, :destroy]

    #材料
    resources :material_details, only:[:index, :new, :create, :edit, :update, :destroy]

    resources :categories, only:[:index, :new, :create, :destroy]
end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
  has_ancestry

  attr_accessor :child_name
  attr_accessor :grandchild_name

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @categories = Category.where(ancestry: nil)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    category_parent = Category.find(params[:category][:id])
    category_children = category_parent.children.create(name: params[:category][:child_name])
    category_children.children.create(name: params[:category][:grandchild_name]) unless params[:category][:grandchild_name].blank?
    redirect_to admin_categories_path
  end

  # def parents
  #   @parents = Category.where(ancestry: nil)
  # end

  # def category_children
  #   @category_children = Category.find("#{params[:parent_id]}").children
  # end

  # def category_grandchildren
  #   @category_grandchildren = Category.find("#{params[:child_id]}").children
  # end

  private

  def category_params
    params.require(:category).permit(:id, :name, :ancestr, :child_name, :grandchild_name)
  end


end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  <ul>
    <% @categories.each do |category| %>
      <li>
        <%= category.name %>
        <ul class="ml-3">
          <% category.children.each do |child| %>
            <li>
              <%= child.name %>
              <ul class="ml-3">
                <% child.children.each do |gchild| %>
                  <li>
                    <%= gchild.name %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>
<%= link_to "カテゴリ作成", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div>
        <%= form_with model: @category,url: admin_categories_path, local:true do |f| %>
          <%= f.label :name, "親カテゴリ", class: "d-flex justify-content-start" %>
          <%= f.collection_select :id, Category.find(1,2,3,4), :id, :name %>
          <%= f.label :child_name, "子カテゴリ", class: "d-flex justify-content-start" %>
          <%= f.text_field :child_name, style:"width: 20%;", class: "form-control mb-3" %>
          <%= f.label :grandchild_name, "孫カテゴリ", class: "d-flex justify-content-start" %>
          <%= f.text_field :grandchild_name, style:"width: 20%;", class: "form-control mb-3" %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>